### ISSUE TITLE
Implement Zig Zag Mitigation Reward System

### ISSUE THREAD

**Issue by Popfizz013** [Popfizz013/DEEP_RACER_HACKATHON#3]
There is a need to implement a updated reward system so that the car may understand that it is more optimal to zig zag less. Hence, this improvement aims to improve the cars race speed.

**Comment by Popfizz013** [comment]
Delegated to Mikayla due to time constraints and Nav not being available .

**Comment by MikaylaReim** [comment]
Implemented reward reduction for extreme steering behaviours.
