### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Popfizz013** [Popfizz013/DEEP_RACER_HACKATHON#6]
Need to update the README with information which is pertinent to the project and shows some of the methods and thinking that was used such as:

1.  Add videos, pictures, Gantt charts 
2.  Describe how work was divided and who did what
3.  Describe some short comings (look at the issues we faced with model 2 and model3)
4.  What did we learn from doing this hackathon 
5. How does our model perform in real life vs in the evaluation simulation

Additionally, add code documentation in accordance with norms, such as using a consistent naming strategy (camelCase). Be creative, what do you think recruiters looking at this project of ours want to see from us and is there anywhere where we really shinned?

**Comment by Nav0431** [comment]
Detailed Documentation Updated by Nav

**Comment by Popfizz013** [comment]
Incorrect information on the README. Needs to be reviewed!
